% This code models the variation of cutoff frequencies and the respective
% steady state input response (True Heading)

% Create standard model parameters
run("./compassControlParameters.m");
run("./gyroControlParameters.m");
testInput = "trueHeading";

% Data save folder location
saveFolderLocation = "analytics/cutoffVariations/long_heading_small_dataset/";
% Vary the cutoff frequencies over the attenuation range of the gyroFiler.
varyingCutoffFrequencies = logspace(-2, 2, 12);

% Compass Constant Parameters
compassFilterGain = 1;

p = 1;
% Iterating Parameters and Simulations
for cutoffFrequencyIteration = varyingCutoffFrequencies
    % Compass Filter Variation
    compassTimeConstant = 1/cutoffFrequencyIteration; % Rad
    compassFilterNumerator = compassFilterGain;
    compassFilterDenominator = [compassTimeConstant 1];
    compassFilterTransferFunction = tf(compassFilterNumerator, compassFilterDenominator);
    
    % Gyro Filter Variation
    gyroTimeConstant = compassTimeConstant;
    gyroFilterNumerator = [1 0];
    gyroFilterDenominator = [1 1/gyroTimeConstant];
    gyroFilterTransferFunction = tf(gyroFilterNumerator, gyroFilterDenominator);
    
    %% SIMULATION
    simulation = sim('fullSystem','SimulationMode','normal');
    % Get results
    simulationData = simulation.get('simulationData');
    assignin('base','simulationData',simulationData);
    
    % Simulation Data
    time = simulationData.time;
    signalsNamesOrdered = ["compassSystem", "compassFilter",...
        "fullSystem", "gyroFilter", "gyroSystem", "input",...
        "compassSystemError", "compassFilterError",...
        "fullSystemError", "gyroSystemError", "gyroFilterError"...
        ].';
    compassSystem = simulationData.signals.values(:, 1);
    compassFilter = simulationData.signals.values(:, 2);
    fullSystem = simulationData.signals.values(:, 3);
    gyroFilter = simulationData.signals.values(:, 4);
    gyroSystem = simulationData.signals.values(:, 5);
    input = simulationData.signals.values(:, 6);
    % Errors
    fullSystemError = fullSystem - input;
    compassSystemError = compassSystem - input;
    compassFilterError = compassFilter - input;
    gyroSystemError = gyroSystem - input;
    gyroFilterError = gyroFilter - input;
    allData = [simulationData.signals.values(:, :),...
               compassSystemError, ...
               compassFilterError, ...
               fullSystemError, ...
               gyroSystemError, ...
               gyroFilterError];
    
    rawDataTable = table(...
        time,...
        compassSystem,...
        compassFilter,...
        fullSystem,...
        gyroFilter,...
        gyroSystem,...
        input,...
        compassSystemError, ...
        compassFilterError, ...
        fullSystemError, ...
        gyroSystemError, ...
        gyroFilterError ...
        );
    writetable(rawDataTable, saveFolderLocation...
    + testInput... 
    + regexprep(string(cutoffFrequencyIteration),'\.','_')...
    + 'Raw.csv');

    % Plot
    figure
    plot(time, compassSystem, time, compassFilter, time, fullSystem,...
          time, gyroFilter, time, gyroSystem, time, input, time, fullSystemError)
    title(num2str(cutoffFrequencyIteration))
    legend(signalsNamesOrdered)
    savefig(saveFolderLocation...
         + testInput... 
         + regexprep(string(cutoffFrequencyIteration),'\.','_')...
         + 'Fig.fig')
    
    
    %% Correlations
    compassSystemFullSystemErrorCrossCorrelation = xcorr(fullSystemError, compassSystem);
    compassFilterFullSystemErrorCrossCorrelation = xcorr(fullSystemError, compassFilter);
    fullSystemFullSystemErrorCrossCorrelation = xcorr(fullSystemError, fullSystem);
    gyroFilterFullSystemErrorCrossCorrelation = xcorr(fullSystemError, gyroFilter);
    gyroSystemFullSystemErrorCrossCorrelation = xcorr(fullSystemError, gyroSystem);
    % Errors
    compassSystemErrorFullSystemErrorCrossCorrelation =  xcorr(fullSystemError, compassSystemError);
    compassFilterErrorFullSystemErrorCrossCorrelation =  xcorr(fullSystemError, compassFilterError);
    fullSystemErrorFullSystemErrorCrossCorrelation =  xcorr(fullSystemError, fullSystemError);
    gyroSystemErrorFullSystemErrorCrossCorrelation =  xcorr(fullSystemError, gyroSystemError);
    gyroFilterErrorFullSystemErrorCrossCorrelation =  xcorr(fullSystemError, gyroFilterError);

    correlationData = [compassSystemFullSystemErrorCrossCorrelation,...
        compassFilterFullSystemErrorCrossCorrelation,...
        fullSystemFullSystemErrorCrossCorrelation, ...
        fullSystemFullSystemErrorCrossCorrelation,...
        gyroFilterFullSystemErrorCrossCorrelation, ...
        gyroSystemFullSystemErrorCrossCorrelation,...
        compassSystemErrorFullSystemErrorCrossCorrelation, ... 
        compassFilterErrorFullSystemErrorCrossCorrelation, ... 
        fullSystemErrorFullSystemErrorCrossCorrelation, ... 
        gyroSystemErrorFullSystemErrorCrossCorrelation, ... 
        gyroFilterErrorFullSystemErrorCrossCorrelation...
        ];

    correlationsDataTable = table(...
        compassSystemFullSystemErrorCrossCorrelation,...
        compassFilterFullSystemErrorCrossCorrelation,...
        fullSystemFullSystemErrorCrossCorrelation,...
        gyroFilterFullSystemErrorCrossCorrelation,...
        gyroSystemFullSystemErrorCrossCorrelation,...
        compassSystemErrorFullSystemErrorCrossCorrelation, ... 
        compassFilterErrorFullSystemErrorCrossCorrelation, ... 
        fullSystemErrorFullSystemErrorCrossCorrelation, ... 
        gyroSystemErrorFullSystemErrorCrossCorrelation, ... 
        gyroFilterErrorFullSystemErrorCrossCorrelation);
    writetable(correlationsDataTable, saveFolderLocation...
    + testInput... 
    + regexprep(string(cutoffFrequencyIteration),'\.','_')...
    + 'Correlations.csv');

    figure
    stackedplot(correlationsDataTable)
    title(num2str(cutoffFrequencyIteration))
    savefig(saveFolderLocation...
        + testInput... 
        + regexprep(string(cutoffFrequencyIteration),'\.','_')...
        + 'CorrelationFig.fig')


    
    %% Signals Processing
    % Raw Signals
    meanSignals = mean(allData(:, :)).';
    standardDeviationSignals = std(allData(:, :)).';
    varianceSignals = var(allData(:, :)).';
    maxSignals = max(allData(:, :)).';
    minSignals = min(allData(:, :)).';
    kurtosisSignals = kurtosis(allData(:, :)).';
    firstMomentSignals = moment(allData(:, :), 1).';
    secondMomentSignals = moment(allData(:, :), 2).';
    thirdMomentSignals = moment(allData(:, :), 3).';
    fourthMomentSignals = moment(allData(:, :), 4).';
    skewnessSignals = skewness(allData(:, :)).';
    rmsSignals = rms(allData(:, :)).';
    powerSignals = powerbw(allData(:, :)).';
    % Correlations
    maxCorrelationSignals = max(correlationData).';
    meanCorrelationSignals = mean(correlationData).';
    standardDeviationCorrelationSignals = std(correlationData).';
    varCorrelationSignals = var(correlationData).';
    kurtosisCorrelationSignals = kurtosis(correlationData).';
    powerCorrelationSignals = powerbw(correlationData).';
    rmsCorrelationSignals = rms(correlationData).';

    %% Display Analytics
    analyticsTable = table(signalsNamesOrdered, maxSignals, minSignals, meanSignals,...
        standardDeviationSignals, varianceSignals, kurtosisSignals,...
        skewnessSignals, firstMomentSignals, secondMomentSignals,...
        thirdMomentSignals, fourthMomentSignals, rmsSignals,...
        powerSignals, maxCorrelationSignals, meanCorrelationSignals,...
        standardDeviationCorrelationSignals, varCorrelationSignals, kurtosisCorrelationSignals,...
        powerCorrelationSignals, rmsCorrelationSignals)
    writetable(analyticsTable ,'analytics/cutoffVariations/longHeading/'...
         + testInput...
         + regexprep(string(cutoffFrequencyIteration),'\.','_')...
         + 'Analytics.csv');
    p = p + 1
    if p > 100
        close all
        p=0;
    end
end
! git add * && git commit -am "Ran long heading" && git push origin master
close all
