%% INITIALIZATION
run("./compassControlParameters.m");
run("./idealCompassFilterParameters.m");
run("./gyroControlParameters.m");
run("./idealGyroFilterParameters.m");
testInput = "trueHeading";

configurationParamtersTable = table(maxMagnitudeFilteredMagnitudeDBSecondOrder, ...
    maxFrequencyFilteredMagnitudeDBSecondOrder, compassTimeConstant, ...
    gyroCutoffFrequency, gyroTimeConstant);
writetable(configurationParamtersTable ,'analytics/' + testInput + 'Configuration.csv');

%% SIMULATION
simulation = sim('fullSystem','SimulationMode','normal');
% Get results
simulationData = simulation.get('simulationData');
assignin('base','simulationData',simulationData);

% Simulation Data
time = simulationData.time;
signalsNamesOrdered = ["compassSystem", "compassFilter",...
    "fullSystem", "gyroFilter", "gyroSystem", "input", "error"].';
compassSystem = simulationData.signals.values(:, 1);
compassFilter = simulationData.signals.values(:, 2);
fullSystem = simulationData.signals.values(:, 3);
gyroFilter = simulationData.signals.values(:, 4);
gyroSystem = simulationData.signals.values(:, 5);
input = simulationData.signals.values(:, 6);
error = fullSystem - input;
allData = [simulationData.signals.values(:, :), error];

rawDataTable = table(...
    time,...
    compassSystem,...
    compassFilter,...
    fullSystem,...
    gyroFilter,...
    gyroSystem,...
    input,...
    error);
writetable(rawDataTable ,'analytics/'...
+ testInput...
+ datestr(now,'_dd_HH_MM_')...
+ 'Raw.csv');

%% Correlations
compassSystemErrorCrossCorrelation = xcorr(error, compassSystem);
compassFilterErrorCrossCorrelation = xcorr(error, compassFilter);
fullSystemErrorCrossCorrelation = xcorr(error, fullSystem);
gyroFilterErrorCrossCorrelation = xcorr(error, gyroFilter);
gyroSystemErrorCrossCorrelation = xcorr(error, gyroSystem);
errorAutoCorrelation =  xcorr(error, error);

correlationData = [compassSystemErrorCrossCorrelation,...
    compassFilterErrorCrossCorrelation, fullSystemErrorCrossCorrelation, ...
    fullSystemErrorCrossCorrelation, gyroFilterErrorCrossCorrelation, ...
    gyroSystemErrorCrossCorrelation, errorAutoCorrelation];

correlationsDataTable = table(...
    compassSystemErrorCrossCorrelation,...
    compassFilterErrorCrossCorrelation,...
    fullSystemErrorCrossCorrelation,...
    gyroFilterErrorCrossCorrelation,...
    gyroSystemErrorCrossCorrelation,...
    errorAutoCorrelation);
writetable(correlationsDataTable,'analytics/'...
+ testInput...
+ "_t_"...
+ datestr(now,'mm-dd-yyyy HH-MM')...
+ 'Correlations.csv');

figure
stackedplot(correlationsDataTable)
savefig("analytics/"...
    + testInput...
    + datestr(now,'_dd_HH_MM_')...
    + 'CorrelationFig.fig')


%% Plot
figure
plot(time, compassSystem, time, compassFilter, time, fullSystem,...
     time, gyroFilter, time, gyroSystem, time, input, time, error)
legend(signalsNamesOrdered)
savefig("analytics/"...
    + testInput...
    + datestr(now,'_dd_HH_MM_')...
    + 'Fig.fig')

%% Signals Processing
% Raw Signals
meanSignals = mean(allData(:, :)).';
standardDeviationSignals = std(allData(:, :)).';
varianceSignals = var(allData(:, :)).';
maxSignals = max(allData(:, :)).';
minSignals = min(allData(:, :)).';
kurtosisSignals = kurtosis(allData(:, :)).';
firstMomentSignals = moment(allData(:, :), 1).';
secondMomentSignals = moment(allData(:, :), 2).';
thirdMomentSignals = moment(allData(:, :), 3).';
fourthMomentSignals = moment(allData(:, :), 4).';
skewnessSignals = skewness(allData(:, :)).';
rmsSignals = rms(allData(:, :)).';
powerSignals = powerbw(allData(:, :)).';
% Correlations
maxCorrelationSignals = max(correlationData).';
meanCorrelationSignals = mean(correlationData).';
standardDeviationSignals = std(correlationData).';
varCorrelationSignals = var(correlationData).';
kurtosisCorrelationSignals = kurtosis(correlationData).';
powerCorrelationSignals = powerbw(correlationData).';
rmsCorrelationSignals = rms(correlationData).';
% overshootSignals = overshoot(fullSystem).';
% undershootSignals = undershoot(fullSystem).';
% settlingTimeSignals = settlingtime(fullSystem).';


%% Display Analytics
analyticsTable = table(signalsNamesOrdered, maxSignals, minSignals, meanSignals,...
    standardDeviationSignals, varianceSignals, kurtosisSignals,...
    skewnessSignals, firstMomentSignals, secondMomentSignals,...
    thirdMomentSignals, fourthMomentSignals, rmsSignals,...
    powerSignals, maxCorrelationSignals, meanCorrelationSignals,...
    standardDeviationSignals, varCorrelationSignals, kurtosisCorrelationSignals,...
    powerCorrelationSignals, rmsCorrelationSignals)
writetable(analyticsTable ,'analytics/'...
     + testInput...
     + datestr(now,'_dd_HH_MM_')...
     + 'Analytics.csv');
%% Spectral Kurtuosis
% i = 1;
% for signalsAmount = 1:6
%     figure
%     pkurtosis(allData(:, i))
%     i = i + 1;
% end

